Models/Bicicleta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Bike.Models
{
    public class Bicicleta
    {

        [Key]
        public int Id { get; set; }

        [DisplayName("Modelo da bicicleta")]
        public string Modelo { get; set; }

        [DisplayName("Valor da bicicleta")]
        public double Valor { get; set; }

        [DisplayName("Quantidade em estoque da bicicleta")]
        public int QtdEstoque { get; set; }

        [DisplayName("Data de cadastro da bicicleta")]
        public string DataCadastro { get; set; }
    }
}

Models/BicicletaDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bike.Models
{
    public class BicicletaDbContext : DbContext
    {
        public BicicletaDbContext(DbContextOptions<BicicletaDbContext> options):base (options)
        {
        }

        public DbSet<Bicicleta> Bicicletas { get; set; }

    }
}

Models/BicicletaRepository.cs

using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;


namespace Bike.Models
{
    public class BicicletaRepository : IBicicletaRepository
    {
        private BicicletaDbContext _context;
        

        public BicicletaRepository(BicicletaDbContext ctx) {
            _context = ctx;
        }

        public IEnumerable<Bicicleta> GetBike()
        {
            return _context.Bicicletas.ToList();
        }

        public Bicicleta GetBikePorID(int id)
        {
            return _context.Bicicletas.Find(id);
        }

        public void InserirBike(Bicicleta bicicleta)
        {
           _context.Bicicletas.Add(bicicleta);
        }

        public void DeletarBike(int BicicletaId)
        {
            Bicicleta bicicleta = _context.Bicicletas.Find(BicicletaId);
            _context.Bicicletas.Remove(bicicleta);
        }

        public void AtualizaBike(Bicicleta bicicleta)
        {
            _context.Entry(bicicleta).State = EntityState.Modified;
        }

        public void Salvar()
        {
            _context.SaveChanges();
        }

        private bool disposed = false;
        protected virtual void Dispose(bool disposing)
        {
            if (!this.disposed)
            {
                if (disposing)
                {
                    _context.Dispose();
                }
            }
            this.disposed = true;
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }



        public IQueryable<Bicicleta> Bicicletas => _context.Bicicletas;
    }
}

Models/ErrorViewModel.cs
using System;

namespace Bike.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/IBicicletaRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Bike.Models
{
    public interface IBicicletaRepository : IDisposable
    {
        IEnumerable<Bicicleta> GetBike();
        Bicicleta GetBikePorID(int BicicletaId);
        void InserirBike(Bicicleta bike);
        void DeletarBike(int BicicletaId);
        void AtualizaBike(Bicicleta bike);
        void Salvar();
    }
}

Controllers/BicicletaController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Web;
using Bike.Models;
using System.Data;

namespace Bike.Controllers
{
    public class BicicletaController : Controller
    {
        private readonly IBicicletaRepository _bicicletaRepositorio;

        public BicicletaController()
        {
            this._bicicletaRepositorio = new BicicletaRepository(new BicicletaDbContext());
        }

        // GET: /Bike/
        public ActionResult Index()
        {
            var bikes = from bike in _bicicletaRepositorio.GetBike()
                        select bike;
            return View(bikes);
        }

        // GET: /Bike/Details/5
        public ActionResult Details(int id)
        {
            Bicicleta bike = _bicicletaRepositorio.GetBikePorID(id);
            return View(bike);
        }

        // GET: /Bike/Create
        public ActionResult Create()
        {
            return View(new Bicicleta());
        }

        // POST: /Bike/Create
        [HttpPost]
        public ActionResult Create(Bicicleta bike)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _bicicletaRepositorio.InserirBike(bike);
                    _bicicletaRepositorio.Salvar();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Não foi possível salvar as mudanças. Tente novamente....");
            }
            return View(bike);
        }

        // GET: /Bike/Edit/5
        public ActionResult Edit(int id)
        {
            Bicicleta bike = _bicicletaRepositorio.GetBikePorID(id);
            return View(bike);
        }

        //
        // POST: /Bike/Edit/5
        [HttpPost]
        public ActionResult Edit(Bicicleta bike)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _bicicletaRepositorio.AtualizaBike(bike);
                    _bicicletaRepositorio.Salvar();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Não foi possível salvar as mudanças. Tente novamente.....");
            }
            return View(bike);
        }

        // GET: /Bike/Delete/5
        public ActionResult Delete(int id, bool? saveChangesError)
        {
            if (saveChangesError.GetValueOrDefault())
            {
                ViewBag.ErrorMessage = "Não foi possível salvar as mudanças. Tente novamente......";
            }
            Bicicleta bike = _bicicletaRepositorio.GetBikePorID(id);
            return View(bike);
        }

        // POST: /Bike/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            try
            {
                Bicicleta bike = _bicicletaRepositorio.GetBikePorID(id);
                _bicicletaRepositorio.DeletarBike(id);
                _bicicletaRepositorio.Salvar();
            }
            catch (DataException)
            {
                return RedirectToAction("Delete",
                  new Routing.RouteValueDictionary {
               { "id", id },
               { "saveChangesError", true } });
            }
            return RedirectToAction("Index");
        }

    }
}

Views/Bicicleta/Create.cshtml
@model Bike.Models.Bicicleta

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Bicicleta</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Modelo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Modelo)
            @Html.ValidationMessageFor(model => model.Modelo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Valor)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Valor)
            @Html.ValidationMessageFor(model => model.Valor)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.QtdEstoque)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.QtdEstoque)
            @Html.ValidationMessageFor(model => model.QtdEstoque)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DataCadastro)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DataCadastro)
            @Html.ValidationMessageFor(model => model.DataCadastro)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Bicicleta/Delete.cshtml
@model Bike.Models.Bicicleta

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Bicicleta</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Modelo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Modelo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Valor)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Valor)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.QtdEstoque)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.QtdEstoque)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DataCadastro)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DataCadastro)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Views/Bicicleta/Details.cshtml
@model Bike.Models.Bicicleta

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<fieldset>
    <legend>Bicicleta</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Titulo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Titulo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Valor)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Valor)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.QtdEstoque)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.QtdEstoque)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DataCadastro)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DataCadastro)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Bicicleta/Edit.cshtml
@model Bike.Models.Bicicleta

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Bicicleta</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Modelo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Modelo)
            @Html.ValidationMessageFor(model => model.Modelo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Valor)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Valor)
            @Html.ValidationMessageFor(model => model.Valor)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.QtdEstoque)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.QtdEstoque)
            @Html.ValidationMessageFor(model => model.QtdEstoque)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DataCadastro)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DataCadastro)
            @Html.ValidationMessageFor(model => model.DataCadastro)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Bicicleta/Index.cshtml
@model IEnumerable<Bike.Models.Bicicleta>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>@Html.DisplayNameFor(model => model.Modelo)</th>
        <th>@Html.DisplayNameFor(model => model.Valor)</th>
        <th>@Html.DisplayNameFor(model => model.QtdEstoque)</th>
        <th>@Html.DisplayNameFor(model => model.DataCadastro)</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>@Html.DisplayFor(modelItem => item.Modelo)
        </td>
        <td>@Html.DisplayFor(modelItem => item.Valor)
        </td>
        <td>@Html.DisplayFor(modelItem => item.QtdEstoque)
        </td>
        <td>@Html.DisplayFor(modelItem => item.DataCadastro)
        </td>
        <td>@Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bike</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Bicicleta" asp-action="Index">Bike</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bicicleta" asp-action="Index">Bicicleta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bicicleta" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Bike - <a asp-area="" asp-controller="Bicicleta" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>